name: nickname
version: '${project.version}'
main: org.uminokun.nickname.Nickname
api-version: '1.20'Q
commands:
  nickname:
    description: ニックネームを変更
    aliases:
      - nick
  editname:
    description: 他人のニックネームを変更
    aliases:
      - edit